services:
  - type: worker   # <-- was "web"
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      # add other envs you actually use (ADMIN_ID, LOG_CHANNEL_ID, etc.)
